/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin Google sign-in
         * @description Sets a short-lived `oauth_state` cookie (CSRF protection) and redirects to
         *     Google's consent screen. Open this in a **browser** — it cannot be completed
         *     from an API client.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google's consent screen. */
                307: {
                    headers: {
                        Location?: string;
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google OAuth callback
         * @description Google redirects here with `code` and `state`. On success the user is
         *     created or refreshed and a `session` JWT cookie is set (24h).
         *
         *     This URI must exactly match the one registered on the Google OAuth client.
         */
        get: {
            parameters: {
                query?: {
                    code?: string;
                    /** @description Must match the `oauth_state` cookie. */
                    state?: string;
                    /** @description Present when the user declines consent. */
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description Always a redirect, because a browser lands here — never a JSON body.
                 *
                 *     On success the `session` cookie is set and the user is sent to
                 *     `FRONTEND_URL`. On failure they are sent to
                 *     `FRONTEND_URL/login?error=<code>`, where the code is one of
                 *     `login_cancelled`, `invalid_state`, `missing_code`, `login_failed`.
                 */
                302: {
                    headers: {
                        Location?: string;
                        /** @description Present only on success. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Lets a SPA bootstrap auth state on load, since the `session` cookie is
         *     httpOnly and cannot be read by JavaScript. A 401 means "not signed in"
         *     and should be treated as a normal state, not an error.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The signed-in user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Clears the `session` cookie. Intentionally unauthenticated, so an
         *     expired or malformed cookie can still be cleared.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Signed out. */
                204: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated user's campaigns
         * @description Newest first. `status` on each row is derived at request time.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user's campaigns. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampaignListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Shorten a URL (find-or-create the destination)
         * @description Two outcomes:
         *
         *     - **201** — the destination is new for this user, so it is created along
         *       with a first campaign, returned as `short_url`.
         *     - **200** — the user already has this destination, so nothing is created
         *       and its existing campaigns are returned as `short_urls`. Any
         *       `campaign_name`/`starts_at`/`expires_at` sent are ignored in this case;
         *       use `POST /api/destinations/{destinationId}/short-urls` to add another campaign.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDestinationRequest"];
                };
            };
            responses: {
                /** @description Destination already existed; its campaigns are returned. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            destination_url: components["schemas"]["DestinationRef"];
                            short_urls: components["schemas"]["ShortURLRef"][];
                        };
                    };
                };
                /** @description Destination created with its first campaign. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            destination_url: components["schemas"]["DestinationRef"];
                            short_url: components["schemas"]["ShortURLRef"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/urls/{shortCode}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortCode: string;
            };
            cookie?: never;
        };
        /** Fetch a single campaign */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The campaign. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            campaign: components["schemas"]["Campaign"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a campaign
         * @description Partial update of `name`, `status`, `starts_at`, `expires_at`.
         *
         *     Validation runs against the **resulting** state, so a single request may
         *     both re-enable a campaign and extend its `expires_at`. Enabling a campaign
         *     whose `expires_at` is already past succeeds but reports `expired`.
         *
         *     A successful update refreshes the redirect cache immediately, so disabling
         *     a campaign stops it redirecting at once.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCampaignRequest"];
                };
            };
            responses: {
                /** @description The updated campaign. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            campaign: components["schemas"]["Campaign"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/urls/{shortCode}/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Click analytics for a campaign
         * @description Two response shapes, selected by whether `group_by` is present:
         *
         *     - **without `group_by`** — the overview: `total_clicks` plus a bucketed
         *       `series` for the trend line.
         *     - **with `group_by`** — a breakdown: `total_clicks` plus `data`, the top
         *       values for that dimension.
         *
         *     The series is deliberately only returned for the overview, so switching
         *     dimensions doesn't recompute a trend the page already has.
         *
         *     **Range**: defaults to the last **7 days**; maximum window is **90 days**
         *     (a larger request is rejected rather than silently truncated). Bucket
         *     granularity follows the window — hourly for ranges of 2 days or less,
         *     daily beyond that.
         *
         *     **Percentages** are relative to `total_clicks`. Rows are capped at
         *     `limit`, so the listed rows may legitimately sum to less than 100%.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Omit for the overview. */
                    group_by?: "country" | "city" | "region" | "device" | "browser" | "os";
                    /** @description RFC3339. Defaults to `end_ts` minus 7 days. */
                    start_ts?: string;
                    /** @description RFC3339. Defaults to now. */
                    end_ts?: string;
                    /** @description Max breakdown rows, busiest first. Ignored for the overview. */
                    limit?: number;
                };
                header?: never;
                path: {
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview or breakdown, depending on `group_by`. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClickAnalytics"];
                    };
                };
                /**
                 * @description Unknown `group_by`, unparseable timestamp, `start_ts` not before
                 *     `end_ts`, or a window longer than 90 days.
                 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/destinations/{destinationId}/short-urls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add another campaign to an existing destination
         * @description Lets one destination carry several short links — e.g. one per marketing
         *     channel — each with its own code, name and schedule.
         *
         *     Keyed by **destination id**. Campaign endpoints live under `/api/urls`
         *     and are keyed by short code, so the two identifier types stay separate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    destinationId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateShortURLRequest"];
                };
            };
            responses: {
                /** @description The new campaign. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            short_url: components["schemas"]["ShortURLRef"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description No such destination, or it belongs to another user. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{shortCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a short link
         * @description Public, unauthenticated. Served from a Redis cache without touching the
         *     database on a hit. Records a click event asynchronously — analytics never
         *     delay or break the redirect.
         *
         *     Returns **302** (not 301) deliberately: a cached permanent redirect would
         *     stop repeat clicks reaching the server, losing analytics.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description First entry is used as the client IP for geo lookup when present. */
                    "X-Forwarded-For"?: string;
                };
                path: {
                    shortCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the destination URL. */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /**
                 * @description Unknown code, or the campaign is `disabled`, `scheduled` or `expired`.
                 *     Indistinguishable by design.
                 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            /** Format: email */
            email: string;
            /** @description Derived from the email local-part at signup. */
            username: string;
            /** @description Google profile picture. */
            image_url?: string | null;
            is_verified: boolean;
            /** Format: date-time */
            verified_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ClickAnalytics: {
            /** @description The range actually used, after defaults were applied. */
            range: {
                /** Format: date-time */
                start_ts: string;
                /** Format: date-time */
                end_ts: string;
            };
            /** @description Clicks in the range. Percentages are relative to this. */
            total_clicks: number;
            /**
             * @description Echoed back; present only on a breakdown.
             * @enum {string}
             */
            group_by?: "country" | "city" | "region" | "device" | "browser" | "os";
            /** @description Breakdown rows, busiest first. Present only with `group_by`. */
            data?: {
                /**
                 * @description The dimension value. Clicks with no value for the dimension
                 *     are folded into a literal `"unknown"` row rather than dropped
                 *     — geo is missing for private IPs and OS for unparseable
                 *     user agents, so this bucket is often significant.
                 */
                value: string;
                clicks: number;
                /** Format: double */
                percentage: number;
            }[];
            /**
             * @description Clicks per time bucket, oldest first. Present only on the overview.
             *     Hourly for ranges up to 2 days, daily beyond.
             */
            series?: {
                /** Format: date-time */
                bucket: string;
                clicks: number;
            }[];
        };
        /**
         * @example {
         *       "error": "short url not found"
         *     }
         */
        Error: {
            /** @description Human-readable failure reason. */
            error: string;
        };
        /**
         * @description Effective campaign status, computed per request:
         *
         *     | Value | Meaning |
         *     |---|---|
         *     | `disabled` | The user paused it. Always wins over the schedule. |
         *     | `scheduled` | `starts_at` is in the future. |
         *     | `expired` | `expires_at` is in the past. |
         *     | `active` | Redirecting right now. |
         *
         *     Only `ACTIVE` and `DISABLED` are accepted as *input* on update.
         * @enum {string}
         */
        ShortURLStatus: "active" | "scheduled" | "expired" | "disabled";
        /** @description A short link and the destination it points at. */
        Campaign: {
            /** @example 9 */
            id: number;
            /**
             * @description The short code appearing in the short link.
             * @example OQ
             */
            code: string;
            /**
             * Format: uri
             * @example http://localhost:8080/OQ
             */
            short_url: string;
            /** @example instagram launch */
            campaign_name: string | null;
            status: components["schemas"]["ShortURLStatus"];
            /**
             * @description Where visitors are sent.
             * @example https://example.com/product/123
             */
            destination_url: string;
            /**
             * Format: date-time
             * @description Before this instant the campaign reports `scheduled` and will not redirect.
             */
            starts_at: string | null;
            /**
             * Format: date-time
             * @description After this instant the campaign reports `expired` and will not redirect.
             */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        DestinationRef: {
            /** @example 5 */
            id: number;
            /** @example https://example.com/product/123 */
            url: string;
        };
        /** @description Compact short-link shape returned by the creation endpoints. */
        ShortURLRef: {
            id: number;
            code: string;
            /** Format: uri */
            url: string;
            campaign_name?: string | null;
            status: components["schemas"]["ShortURLStatus"];
        };
        /**
         * @example {
         *       "destination_url": "https://example.com/product/123",
         *       "campaign_name": "instagram launch"
         *     }
         */
        CreateDestinationRequest: {
            /** @description The long URL to shorten. */
            destination_url: string;
            campaign_name?: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        /**
         * @description Adds another campaign to a destination that already exists.
         * @example {
         *       "campaign_name": "email campaign",
         *       "expires_at": "2027-01-01T00:00:00Z"
         *     }
         */
        CreateShortURLRequest: {
            campaign_name?: string | null;
            /** Format: date-time */
            starts_at?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        /**
         * @description A partial update. **Omitting a key leaves it unchanged; sending `null`
         *     clears it.** `{}` is a valid no-op.
         * @example {
         *       "name": "renamed campaign",
         *       "status": "DISABLED"
         *     }
         * @example {
         *       "expires_at": null
         *     }
         */
        UpdateCampaignRequest: {
            /** @description Send `null` to remove the campaign name. */
            name?: string | null;
            /**
             * @description Case-insensitive. Sending `SCHEDULED` or `EXPIRED` returns 400 —
             *     those are derived from the dates, not settable.
             * @enum {string}
             */
            status?: "ACTIVE" | "DISABLED";
            /**
             * Format: date-time
             * @description Send `null` to start immediately.
             */
            starts_at?: string | null;
            /**
             * Format: date-time
             * @description Send `null` to make the campaign never expire.
             */
            expires_at?: string | null;
        };
        CampaignListResponse: {
            campaigns: components["schemas"]["Campaign"][];
            /** @description Total campaigns owned by the user, ignoring pagination. */
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description Missing, expired or invalid session cookie. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthorized"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description No such short code, **or** it belongs to another user. The two are
         *     deliberately indistinguishable so campaign ownership isn't leaked.
         */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "short url not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed body or a patch that would leave the campaign invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "expires_at must be after starts_at"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
